version: '3.8'

x-service-base: &service-base
     init: true
     restart: unless-stopped

x-volume-base: &volume-base
     driver: local
     driver_opts: &driver-opts
          o: bind
          type: none

x-env-db-base: &env-db
     DB_NAME: ${DB_NAME}
     MARIADB_HOST: ${MARIADB_HOST}
     DB_ROOT_PASSWD: ${DB_ROOT_PASSWD}
     DB_ADMIN: ${DB_ADMIN}
     DB_ADMIN_PASSWD: ${DB_ADMIN_PASSWD}
     DB_USER: ${DB_USER}
     DB_USER_PASSWD: ${DB_USER_PASSWD}

x-env-wp-base: &env-wp
     WWW_DIR: ${WWW_DIR}
     URL: ${URL}
     WP_ADMIN: ${WP_ADMIN}
     WP_ADMIN_PASSWD: ${WP_ADMIN_PASSWD}
     WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
     WP_USER: ${WP_USER}
     WP_USER_PASSWD: ${WP_USER_PASSWD}
     WP_USER_EMAIL: ${WP_USER_EMAIL}
     WP_REDIS_HOST: ${WP_REDIS_HOST}
     WP_REDIS_DB: ${WP_REDIS_DB}

x-env-ftp-base: &env-ftp
     FTP_HOST: ${FTP_HOST}
     FTP_USER: ${FTP_USER}
     FTP_PWD: ${FTP_PASS}

services:
     nginx:
          <<: *service-base
          build:
               context: ./requirements/nginx
          image: nginx
          volumes:
               - wordpress-volume:/var/www/${DOMAIN_NAME}:ro
               - adminer-volume:/var/www/adminer:ro
               - static-page-volume:/var/www/static-page:ro
          networks:
               - nginx-network
          ports:
               - '443:443'
          depends_on:
               - mariadb
               - wordpress

     mariadb:
          <<: *service-base
          build:
               context: ./requirements/mariadb
          image: mariadb
          volumes:
               - mariadb-volume:/var/lib/mysql:rw
          environment:
               <<: *env-db
          networks:
               - DB-network

     wordpress:
          <<: *service-base
          build:
               context: ./requirements/wordpress
               args:
                    - WWW_DIR=${WWW_DIR}
          image: wordpress
          environment:
               <<: *env-db
               <<: *env-wp
          volumes:
               - wordpress-volume:${WWW_DIR}:rw
          networks:
               - DB-network
               - nginx-network
               - redis-network
          depends_on:
               - mariadb

     static-page:
          <<: *service-base
          build:
               context: ./requirements/bonus/static-page
          image: static-page
          networks:
               - nginx-network
          volumes:
               - static-page-volume:/var/www/static-page:ro

     adminer:
          <<: *service-base
          build:
               context: ./requirements/bonus/adminer
          image: adminer
          networks:
               - DB-network
               - nginx-network
          depends_on:
               - mariadb
          volumes:
               - adminer-volume:/var/www/adminer:ro

     redis-cache:
          <<: *service-base
          build:
               context: ./requirements/bonus/redis-cache
          image: redis-cache
          networks:
               - redis-network

     ftp:
          <<: *service-base
          build:
               context: ./requirements/bonus/ftp
          image: ftp
          volumes:
               - wordpress-volume:/home/${FTP_USER}/wordpress:rw
          environment:
               <<: *env-ftp
          ports:
               - "21:21"
               - "21100-21110:21100-21110"
          depends_on:
               - wordpress

     backup:
          <<: *service-base
          image: backup
          build:
               context: ./requirements/bonus/backup
          depends_on:
               - mariadb
          volumes:
               - bk-volume:/bk:rw
               - mariadb-volume:/db:rw
          init: true

volumes:
     mariadb-volume:
          <<: *volume-base
          driver_opts:
               device: /home/${USER}/data/db_data
               <<: *driver-opts

     wordpress-volume:
          <<: *volume-base
          driver_opts:
               device: /home/${USER}/data/wp_data
               <<: *driver-opts

     bk-volume:
          <<: *volume-base
          driver_opts:
               device: /home/${USER}/data/backup
               <<: *driver-opts

     adminer-volume:

     static-page-volume:

networks:
     nginx-network:

     DB-network:

     redis-network:
