version: '3.8'

x-service-base: &service-base
     init: true
     restart: unless-stopped

x-volume-base: &volume-base
     driver: local
     driver_opts: &driver-opts
          o: bind
          type: none

x-env-db-base: &env-db
     DB_NAME: ${DB_NAME}
     MARIADB_HOST: ${MARIADB_HOST}
     DB_ROOT_PASSWD: ${DB_ROOT_PASSWD}
     DB_ADMIN: ${DB_ADMIN}
     DB_ADMIN_PASSWD: ${DB_ADMIN_PASSWD}
     DB_USER: ${DB_USER}
     DB_USER_PASSWD: ${DB_USER_PASSWD}

x-env-wp-base: &env-wp
     WWW_DIR: ${WWW_DIR}
     URL: ${URL}
     WP_ADMIN: ${WP_ADMIN}
     WP_ADMIN_PASSWD: ${WP_ADMIN_PASSWD}
     WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
     WP_USER: ${WP_USER}
     WP_USER_PASSWD: ${WP_USER_PASSWD}
     WP_USER_EMAIL: ${WP_USER_EMAIL}

services:
     nginx:
          <<: *service-base
          build:
               context: ./requirements/nginx
          image: nginx
          volumes:
               - wordpress-volume:/var/www/${DOMAIN_NAME}:ro
               - adminer-volume:/var/www/adminer:ro
               - static-page-volume:/var/www/static-page:ro
          networks:
               - nginx-network
          ports:
               - '443:443'
          depends_on:
               - mariadb
               - wordpress

     mariadb:
          <<: *service-base
          build:
               context: ./requirements/mariadb
          image: mariadb
          volumes:
               - mariadb-volume:/var/lib/mysql:rw
          environment:
               <<: *env-db
          networks:
               - DB-network

     wordpress:
          <<: *service-base
          build:
               context: ./requirements/wordpress
               args:
                    - WWW_DIR=${WWW_DIR}
          image: wordpress
          environment:
               <<: *env-db
               <<: *env-wp
          volumes:
               - wordpress-volume:${WWW_DIR}:rw
          networks:
               - DB-network
               - nginx-network
          depends_on:
               - mariadb

     static-page:
          <<: *service-base
          build:
               context: ./requirements/bonus/static-page
          image: static-page
          networks:
               - nginx-network
          volumes:
               - static-page-volume:/var/www/static-page:ro

     adminer:
          <<: *service-base
          build:
               context: ./requirements/bonus/adminer
          image: adminer
          networks:
               - DB-network
               - nginx-network
          depends_on:
               - mariadb
          volumes:
               - adminer-volume:/var/www/adminer:ro

#     ftp-server:
#          <<: *service-base
#          build:
#               context: ./requirements/bonus/ftp-server
#          image: ftp-server
#          volumes:
#               - wordpress-volume:/home/cberganz
#          networks:
#               - wp-network
#          ports:
#               - "21:21"
#               - "20:20"
#          depends-on:
#               - wordpress
#
volumes:
     mariadb-volume:
          <<: *volume-base
          driver_opts:
               device: /home/charles/data/db_data
               <<: *driver-opts

     wordpress-volume:
          <<: *volume-base
          driver_opts:
               device: /home/charles/data/wp_data
               <<: *driver-opts

     adminer-volume:

     static-page-volume:

networks:
     nginx-network:

     DB-network:
