CREATE DATABASE DB_NAME;

ALTER USER 'root'@'localhost' IDENTIFIED BY 'DB_ROOT_PASSWD';
GRANT ALL ON *.* TO 'root'@'localhost' WITH GRANT OPTION;

CREATE USER IF NOT EXISTS 'DB_ADMIN'@'%' IDENTIFIED BY 'DB_ADMIN_PASSWD';
GRANT ALL ON *.* TO 'DB_ADMIN'@'%' WITH GRANT OPTION;

CREATE USER IF NOT EXISTS 'DB_USER'@'%' IDENTIFIED BY 'DB_USER_PASSWD';
GRANT ALL PRIVILEGES ON DB_NAME.* TO 'DB_USER'@'%';

FLUSH PRIVILEGES;
