DELETE FROM	mysql.user WHERE User='';
DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');

CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'DB_ROOT_PASSWD';
SET PASSWORD FOR 'root'@'localhost' = PASSWORD('DB_ROOT_PASSWD');

CREATE DATABASE DB_NAME;

CREATE USER IF NOT EXISTS 'DB_ADMIN'@'localhost' IDENTIFIED BY 'DB_ADMIN_PASSWD';
SET PASSWORD FOR 'DB_ADMIN'@'localhost' = PASSWORD('DB_ADMIN_PASSWD');
GRANT ALL ON *.* TO 'DB_ADMIN'@'localhost' WITH GRANT OPTION;

CREATE USER IF NOT EXISTS 'DB_USER'@'%' IDENTIFIED BY 'DB_USER_PASSWD';
GRANT ALL PRIVILEGES ON DB_NAME.* TO 'DB_USER'@'%';

FLUSH PRIVILEGES;
