DELETE FROM	mysql.user WHERE User='';
DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');

CREATE DATABASE DB_NAME;

CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'DB_ROOT_PASSWD';
GRANT ALL ON *.* TO 'root'@'%' WITH GRANT OPTION;

CREATE USER IF NOT EXISTS 'DB_ADMIN'@'%' IDENTIFIED BY 'DB_ADMIN_PASSWD';
GRANT ALL ON *.* TO 'DB_ADMIN'@'%' WITH GRANT OPTION;

CREATE USER IF NOT EXISTS 'DB_USER'@'%' IDENTIFIED BY 'DB_USER_PASSWD';
GRANT ALL PRIVILEGES ON DB_NAME.* TO 'DB_USER'@'%';

FLUSH PRIVILEGES;
